= About
Mike Truso
2017-11-17
:jbake-type: post
:jbake-tags: guild,history,about
:jbake-status: published

The St. Isidore Guild was founded in 2013 to band together Catholic IT professionals. Groups such as the
link:http://www.cathmed.org/[Catholic Medical Association] gather periodically for prayer, fellowship, and discussion on trends in their field.
Why shouldn't technologists do the same? With IT being such a fast paced field it is imperative that experts
in Computer Science who think with the mind of the Church gather to help each other grow professionally and
most importantly give critical thought on how best to develop new technology that contributes to human flourishing.

*Ready to join the conversation?* Contact link:https://twitter.com/miketruso[Mike Truso] to join the Slack group.

=== Guild Activities

Guild activities range from informal meetups at a local brew pub to more formal morning workshops.
Our workshops follow a structure of Mass, breakfast, lecture, discussion. After nourishing the soul with Holy Mass,
we nourish the body with delicious food and catch up on what everyone is working on. A formal talk follows, with discussion
or an activity. From the broad range of expertise of our members, these workshops serve as an excellent opportunity to
get a quick sense of where the industry is moving as well as dive deeper into specific topics.

==== Past Workshops:

- Benefits of Agile Development and correlations to the spiritual life
- Lessons in UX Design
- Educating Children with Programming Techniques
- Net Neutrality, a History
- Open Source Software Trends
- Edward Snowden, Hero or Traitor?
